### ISSUE TITLE
Running issue (Could not find blastn)

### ISSUE THREAD

**Issue by muzzamil1234** [INSaFLU/docker#21]
Hello, Today i download fresh insaflu git and build it after build i run using ./up.sh and facing the following problem. 

Attaching to insaflu-server
insaflu-server  | Traceback (most recent call last):
insaflu-server  |   File "/usr/local/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
insaflu-server  |     self.connect()
insaflu-server  |   File "/usr/local/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
insaflu-server  |     self.connection = self.get_new_connection(conn_params)
insaflu-server  |   File "/usr/local/lib64/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
insaflu-server  |     connection = Database.connect(**conn_params)
insaflu-server  |   File "/usr/local/lib64/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
insaflu-server  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
insaflu-server  | psycopg2.OperationalError: could not connect to server: Connection timed out
insaflu-server  | 	Is the server running on host "db_insaflu" (10.1.0.2) and accepting
insaflu-server  | 	TCP/IP connections on port 5432?

**Comment by dsobral** [comment]
Hello,

This time apparently blast didn't get installed. The yum error code in this case didn't report it as failure so the build continued although blast wasn't installed.
 
The simplest is to try to build again from scratch.

Since the build was finished, you can try "fixing" the existing container by manually installing blast on the fly, though that may be a little bit tricky due to the restart policy of that container (it restarts every ~45s since it is failing). 

For this, you should stop the containers, change the restart policy in docker_compose.yml to 'no', and restart the service (running up.sh again). Then you can get inside the insaflu-server container (using `docker exec -it insaflu-server bash`) and install the missing software (in this case, running 'yum install https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-1.x86_64.rpm'). If successfull, you get exit the container, and restart the service (optionally changing the restart policy to on-failure again).
 
Regards,
Daniel

**Comment by dsobral** [comment]
This error is probably because part of the services are not running, namely the database service.
You should make sure all containers are stopped, and then do ./up.sh (which will guarantee all necessary services are up)

**Comment by muzzamil1234** [comment]
Thanks for quick response. now its stopped all conatainers and re run, now its running but stuck at 
insaflu-server  |    Starting Grid Engine qmaster
insaflu-server  |    Starting Grid Engine execution daemon
insaflu-server  | /insaflu_web/INSaFLU
insaflu-server  | ---> Start apache server  ...
insaflu-server  | httpd not running, trying to start
insaflu-server  | ---> apache running  ...

**Comment by dsobral** [comment]
Hello.

This means everything should be running.
open your browser and go to 127.0.0.1:8080  [or the port that you defined in the .env file]

If you still cannot see anything, then usually this fixes it:
> ctrl^c
> chmod -R 777 $BASE_PATH_DATA/insaflu/log  [where $BASE_PATH_DATA is the folder you defined in .env]
> ./up.sh

If you want the service to run in the background, instead of up.sh just do:
> docker compose up insaflu-server -d

If you see a 400 error, this means you are not running in localhost and need to change the .env file by adding the IP of your machine in the ALLOWED_HOSTS field and restart the containers.

Best,
Daniel
