### ISSUE TITLE
up.sh problem

### ISSUE THREAD

**Issue by mlpereira87** [INSaFLU/docker#22]
When I run up.sh script in the docker directory (after installing INSAFLU and TELEVIR through docker), the following happens:

![image](https://github.com/INSaFLU/docker/assets/54803335/54832ee6-42f7-4838-a1db-0035eeff4477)

In the web browser:

![image](https://github.com/INSaFLU/docker/assets/54803335/7f7f8ef9-7f77-4d86-ad43-d0b21bd83168)

**Comment by dsobral** [comment]
I haven't fully diagnosed why this happens, but I think it's because $BASE_PATH_DATA/insaflu/log/httpd is handled by the root user inside the container and somehow the container cannot write anything inside that folder, causing httpd to be in an error state (because it cannot write the logs).

This usually fixes it for me:
> ctrl^c
> chmod -R 777 $BASE_PATH_DATA/insaflu/log [where $BASE_PATH_DATA is the folder you defined in .env]
.> /up.sh
If you want the service to run in the background, instead of up.sh just do:
docker compose up insaflu-server -d

If you see a 400 error, this means you are not running in localhost and need to change the .env file by adding the IP of your machine (in this case it seems to be 10.101.34.77) in the ALLOWED_HOSTS field and restart the containers.

Hope it helps,
Daniel

**Comment by muzzamil1234** [comment]
![Screenshot from 2023-06-23 17-14-25](https://github.com/INSaFLU/docker/assets/137260213/22dfb0c2-1e40-42d5-b829-ef8031a947a5)

**Comment by dsobral** [comment]
The configuration looks OK.

Make sure all services are running.

I assume that machine 39.22.240.13 is allowing the port 8080 to be visible to the outside (ie can you launch other services using that port?).

Sometimes restarting the apache inside the container helps:
docker exec -it insafu-server restart-apache

Daniel

**Comment by mlpereira87** [comment]
I did the chmod 777 and added the ip into the .env file, like @muzzamil1234 did and:

![image](https://github.com/INSaFLU/docker/assets/54803335/b99b2fb8-0e08-4dcc-a7b4-1103aa81626f)

In the browser:

![image](https://github.com/INSaFLU/docker/assets/54803335/834317a7-de59-4c72-b8c0-bf83554223ee)

Also tried in the localhost browser and it was the same

**Comment by dsobral** [comment]
Apparently it is not assuming the .env file

Let's first make sure the IP is in the .env ALLOWED_HOSTS line inside the container.

Go in the container:
> docker exec -it insaflu-server bash
> cd /insaflu_web/INSaFLU
Edit the .env file to and make sure the IP 10.101.34.77 is in the ALLOWED_HOSTS line (if not, add it and save the file)
Restart apache.
docker exec -it insaflu-server restart-apache

Daniel

**Comment by mlpereira87** [comment]
Now it's working! Thank you!

**Comment by dsobral** [comment]
Thank you for the patience.

We'll try to have a more convenient prebuilt image as soon as possible.

Daniel
